---
title: "Chapter 1"
author: Logan | Nick
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.1 Populations, Samples, and Processes

Statistics provides methods for organizing and summarizing data and for drawing conclusions from that data

Def
---

Data : a collection of facts

Def
---

Population : A well defined collection of objects for which we wish to obtain info

Def
---

Census : When desired info is obtained from every member of the population

 - problems : Time, money, practical

Def
---

Sample : A subset of the population

1. 
---

You want the home price in Edwardsville

 - Fewer well trained appraisers gives better results than many poorly trained 

2. Tree Age Study
---

Testing is destructive, so a sample is better

Def
---

variable : any characteristic whose clue may differ from one subhect to another.

 - denote with low letters
**Note** 
    
    - Don't say $McDonald's = 10$
    - Do say $x = $ the length of the tibia bone in 10 year old boys.
